### ISSUE TITLE
Android tts rate doesn't calculated properly

### ISSUE THREAD

**Issue by maslianok** [ak1394/react-native-tts#10]
The speed of tts is very important for us.
That's why we made some investigation on this. And here are our results:
![unnamed](https://cloud.githubusercontent.com/assets/3485490/22360728/20c53682-e485-11e6-9f77-b79a3081f54c.png)

As you can see, the max rate for Android is ~5. The max rate that we can currently set with help of this library is 3. It's almost twice less...

Moreover, the max rate may differ between different voices.

That's why I would ask you to remove this smart transformation from iOS to Android rate.
Or, maybe, it would be better to add the third parameter to the `setDefaultRate` method. Something like `dontTransform` or whatever...

**Comment by ak1394** [comment]
I would like to provide unified API for setting the rate on Android and iOS. It's easy to pass the unmodified value, but then applications which use the api will have to check which platform they run on.

Is your app available on both Android and iOS? If so, what approach do you use for setting the rate values?

I will provide the way to bypass translation, if we can't figure out way to make translation work for you.

**Comment by maslianok** [comment]
RN has [`Platform`](https://facebook.github.io/react-native/docs/platform-specific-code.html) module that solves our problem.

TTS engines are very different on iOS and Android, so we just have no choice. We have different formulas to calculate `rate` and we need an ability to set this rate without any transformations.

Could you maybe add an additional argument to the `setDefaultRate` method? And just skip this transformation when the parameter equals to `true`.

**Comment by ak1394** [comment]
In v.1.1.0 added optional parameter to setDefaultRate() to turn off transformation.
