### ISSUE TITLE
Add React Native 0.60 support

### ISSUE THREAD

**Issue by thomasaelbrecht** [ak1394/react-native-tts#123]
### Description
Since React Native 0.60.x is working with Cocoapods, we need to add this project's podspec to the Podfile in the ios folder. Without the podspec, I am getting the following error: `NativeModule cannot be null`. The solution below solved this issue.

### Solution
Add the following line below the last podspec in the `Podfile` in the `ios` folder.
```
pod 'TextToSpeech', :podspec => '../node_modules/react-native-tts/TextToSpeech.podspec'
```

Then install all pods with the following command.
```
pod install
```

Hope this helps, it may be usefull to add a note in the README @ak1394.

**Comment by alexking** [comment]
Hm, it worked with autolinking for me - just needed to run `cd ios; pod install` and restart the metro bundler. I'm using a fresh 0.60.x project though so maybe it's only an issue with upgrades?

**Comment by ThiagoLAMF** [comment]
I'm new with react and expo and i'm having this problem with ubuntu+ios, can i install pod in ubuntu?
