### ISSUE TITLE
Is talking status? 

### ISSUE THREAD

**Issue by nicolasgere** [ak1394/react-native-tts#13]
First, thanks for you library ! very usefull
I just ask, if it's possible to know if the voice currently talking or not?

**Comment by ak1394** [comment]
Thanks, thats nice to know!

To keep track of talking/not talking you'd have to subscribe to events with:

Tts.addEventListener('tts-start', (event) => console.log("start", event));
Tts.addEventListener('tts-finish', (event) => console.log("finish", event));

and track it in you program, by perhaps setting a variable.

**Comment by nicolasgere** [comment]
Thanks you may be i will do a pull request for provide an easy way :) 
have a good day

**Comment by ak1394** [comment]
Yeah, go for it!
