### ISSUE TITLE
Is there a way to pause in a sentence?

### ISSUE THREAD

**Issue by bkioshn** [ak1394/react-native-tts#142]
I want to pause a sentence at a specific point, for example when it encounters a space bar or something, so the flow is the same as when we talk.

**Comment by bkioshn** [comment]
I found a solution just add ' . ' for language that doesn't have full stop.

**Comment by EtainLove** [comment]
@bkioshn could you explain how you did it?
add '.' to where?

**Comment by bkioshn** [comment]
> @bkioshn could you explain how you did it?
> add '.' to where?
@EtainLove 
Hmmm It has been a while, but I think adding '.' in the sentence works (Like a full stop).

**Comment by EtainLove** [comment]
@bkioshn 
Ah thanks.
I misunderstood the issue.
I am looking for "pause" the TTS, not the pause between sentences.
