### ISSUE TITLE
Couldn't subscribe to event listeneres

### ISSUE THREAD

**Issue by miooim** [ak1394/react-native-tts#15]
Hello!

I was trying to use the component and managed to set it up.
It does talk, but when I try to subscribe to events the call back is not being called, for example:
`Tts.addEventListener('tts-start', (event) => {
        console.log("tts-start", event);
        dispatch({type: 'SPEECH_STARTED', payload: event});
 });`

Do you have any clue why this could happen?

**Comment by ak1394** [comment]
Well, your code looks okay. What platform you're on? Did you try in simulator or on device?

**Comment by miooim** [comment]
I've tried simulator as of now. API 25.

**Comment by ak1394** [comment]
I tried it on the emulator,  it works for me:


```

componentWillMount() {
  Tts.addEventListener('tts-start', (event) => console.log("start", event));
  Tts.addEventListener('tts-finish', (event) => console.log("finish", event));
  Tts.addEventListener('tts-cancel', (event) => console.log("cancel", event));
}

render() {
  Tts.speak('Hello, world!');
  ...
}
```

How are you checking for logs? Try ``react-native log-android``
