### ISSUE TITLE
Opens Google text to speech on play store, even when it's already installed

### ISSUE THREAD

**Issue by SergiOnGit** [ak1394/react-native-tts#158]
Hello,

On some android devices it opens google text to speech on play store and asks to install even it is installed. It does this everytime on those devices. Can anyone help? Android version doesn't matter, users caught it on android 8,9,10 and even 11.

**Comment by yoursinger** [comment]
I met the same problem.When I use android devices.And When I use the simulator,it's not.Android 11,MIUI 12.5

**Comment by SergiOnGit** [comment]
@yoursinger Thank you. Would be great if plugin author implements it or mention in installation steps. @ak1394
