### ISSUE TITLE
minSdkVersion incompatible with React Native 0.41.2

### ISSUE THREAD

**Issue by jsochurek** [ak1394/react-native-tts#16]
This package has a minSdkVersion=15 build.gradle, however React Native 0.41.2 won't work with less than 16, and the gradle will not sync, giving an AndroidManifest merge error.  I tried to override the requirement but that did not work (RN possibly has GradleOverrides set).

If I change the minSdkVersion in this package to 16, gradle syncs

**Comment by ak1394** [comment]
Ok! I'll update minSdkVersion and publish new release in a day or two.
