### ISSUE TITLE
Change "s.dependency 'React'" to "s.dependency 'React-Core'"

### ISSUE THREAD

**Issue by ngocdaothanh** [ak1394/react-native-tts#173]
I'm using this script:
https://gist.github.com/HosseinRashno/4786b289356ad9840b6c087ce8191fe4

to check
https://github.com/ak1394/react-native-tts/blob/master/TextToSpeech.podspec

and it says:

```
Detected podspec with wrong dependency ----> node_modules/react-native-tts/TextToSpeech.podspec
Fixed podspec with wrong dependency ----> node_modules/react-native-tts/TextToSpeech.podspec
```

**Comment by ak1394** [comment]
Thanks! Can you test current master, to see if it works for you?

**Comment by ngocdaothanh** [comment]
I believe it should work. There are many libraries using and switching to `React-Core`, so no worries.

**Comment by ak1394** [comment]
Cool, it'll go to the next release then!
