### ISSUE TITLE
Could not resolve dependency:     npm ERR! peer react@"17.0.1" from react-native-windows@0.64.1

### ISSUE THREAD

**Issue by allenmanning** [ak1394/react-native-tts#174]
I don't plan on deploying my apps on windows, but I do want TTS.  In order for me to upgrade to 4.0 I need to include this library.  Is this by design?  You must have ` react-native-windows` whether you are going to use it or not?

**Comment by ak1394** [comment]
Sorry, this was unintentional. react-native-windows dependency has been removed in 4.1.0

**Comment by allenmanning** [comment]
Thank you!
