### ISSUE TITLE
Using a headphone on Android only hear 1 earphone

### ISSUE THREAD

**Issue by thuannd7** [ak1394/react-native-tts#176]
When I use headphones on Android I can only hear one side of the headphones and the other side has no sound.
Can you show me why? Thank you

```
Tts.speak(text, {
        androidParams: {
            KEY_PARAM_PAN: -1,
            KEY_PARAM_VOLUME: 1,
            KEY_PARAM_STREAM: 'STREAM_MUSIC',
        },
    });
```

**Comment by ak1394** [comment]
Hi  thuannd7 ! This does not look like an issue with react-native-tts itself. I'm going to close this issue. Could you post your question to Discussions instead https://github.com/ak1394/react-native-tts/discussions
