### ISSUE TITLE
Audio when app is in background

### ISSUE THREAD

**Issue by fungilation** [ak1394/react-native-tts#18]
Thanks for this great library, works great in my app.

Is there a way to get this library to work while app is in background, so speech continues without app interactivity, when multiple paragraphs have already been queued in the TTS library? I see other audio libraries that can play in background, but those are not for TTS, only audio streaming from remote sources.

Any direction is appreciated for having queued TTS playing in background.

**Comment by ak1394** [comment]
You're welcome! Unfortunately I have no experience with background audio, so I can't really help with this one. The library is just a thin layer on top of relevant platform APIs, so it might be a good idea to look into relevant platform documentation and try to apply it to your app.

**Comment by reyalpsirc** [comment]
For iOS, I've been able to do it using the code on [https://stackoverflow.com/questions/19183591/avspeechsynthesizer-in-background-mode/19200177#19200177](https://stackoverflow.com/questions/19183591/avspeechsynthesizer-in-background-mode/19200177#19200177) and also using [react-native-background-timer](https://github.com/ocetnik/react-native-background-timer) to speak some text while the App was in background.

**Comment by fungilation** [comment]
That's cool. Where do you put the native code from stackoverflow though?

**Comment by reyalpsirc** [comment]
@fungilation I've put it on the **AppDelegate.m** of my project, just before the calls of **jsCodeLocation** inside the **didFinishLaunchingWithOptions** function

Also, don't forget to enable the "Audio and AirPlay" in background modes on XCode => Your project on the left  pane => Capabilities

**Comment by ishigamii** [comment]
@reyalpsirc anything similar for Android ?

**Comment by reyalpsirc** [comment]
@ishigamii Sorry, I don't remember. I think I didn't need anything extra for the Android side.

**Comment by ishigamii** [comment]
@reyalpsirc oh that's strange maybe I am missing something cause the queue stops when going into background :s 
@fungilation what about you ? no configuration for android playing in background the queue ?

**Comment by ishigamii** [comment]
@reyalpsirc I did try it but I am pretty sure it will but my case is a bit different. I have a queue of sentence that are not yet queue into tts. I add them as they are read by the tts. And even if I wanted I wouldn't be able to queue all the sentences beforehand. That's why I want my app to keep working in background. On iOS the solution is working perfectly so far as the tts events keeps getting catch and continue to speak. But in android as soon as I leave the app the tts events are not received anymore and so the current sentence finish but the next one doesn't. 

Btw this lib is not updated anymore, any alternative ? 💃

**Comment by reyalpsirc** [comment]
@ishigamii I don't know of any other library :/. Do you have **react-native-background-timer** already set? And if so, do you know if the code set using that library is invoked on background on Android? Because it might be a problem on that library instead or in the way it is invoked

**Comment by ishigamii** [comment]
@reyalpsirc I didn't add this lib to my app yet but I will try to see if it helps 👍

**Comment by ideffix** [comment]
Hi, have anyone found solution how to use tts in background in Android? Im pretty sure that Endomondo is doing that

**Comment by emcee22** [comment]
If you want sounds to work on iOS in background mode you need to do 2 things:

1. enable audio capabilities in xcode
2. configure `AVAudioSession`. There is already a package for it here: https://github.com/BonnierNews/react-native-audio-session

I did this at the root of the project, using 'react-native-sound', but should be the same with audio-session from above.
`
import Sound from 'react-native-sound';
// this will play sound in background
Sound.setCategory('Playback');
`
Somewhere in your background runner:
`Tts.speak('Some text);`

**Comment by mandrewsan** [comment]
In case it helps anyone, I upgraded to React Native 0.79.2, and my setup of `react-native-audio-session` to use `react-native-tts` in the background kept getting killed by iOS after about a minute of playing. After spinning my wheels for several days, I upgraded to 0.80.0 and the problem resolved itself.
