### ISSUE TITLE
Sending `tts-...` with no listeners registered.

### ISSUE THREAD

**Issue by ikejs** [ak1394/react-native-tts#194]
Receiving yellow console warning when calling Tts.speak(word)
- On node 14.15.4
- Calling Tts with TouchableOpacity

![Screen Shot 2021-09-15 at 12 19 07 PM](https://user-images.githubusercontent.com/6834907/133479896-66fcfd65-53f1-45ac-a52f-8633904cdba8.png)

<img src="https://user-images.githubusercontent.com/6834907/133479906-b5466b9f-2298-4eae-89aa-7143092ca6f4.png" width="300px">

<img src="https://user-images.githubusercontent.com/6834907/133479911-a288266d-6995-4ccd-a6b2-b5f2b79f9bca.png" width="300px">

<img src="https://user-images.githubusercontent.com/6834907/133479920-4d7e1b92-b7a3-4f92-b7f9-640de368a5a0.png" width="300px">

## Temporary solution
```js
const ee = new NativeEventEmitter(NativeModules.TextToSpeech);
ee.addListener('tts-start', () => {});
ee.addListener('tts-finish', () => {});
ee.addListener('tts-cancel', () => {});
```

**Comment by ak1394** [comment]
I don't think there is a need to fix it, but thanks for providing way to silence them. You probably could do 

    Tts.addEventListener('tts-start', () => {});
    ...
as well.
