### ISSUE TITLE
Not working for few BCP-47 language code

### ISSUE THREAD

**Issue by stardev24** [ak1394/react-native-tts#197]
I have tried setting language with the BCP-47  language code te-IN

<img width="609" alt="Screenshot 2021-11-06 at 12 48 06 PM" src="https://user-images.githubusercontent.com/13711150/140601553-3ff4e641-fae9-45a4-80bb-cd3cfe3c410b.png">

Expected behaviour:
Audio should come in specified language

Current behaviour:
No audio

Do we have support for all languages?

**Comment by ak1394** [comment]
The support for the particular language depends on underlying platform (iOS/Android). If there is no support for it on the handset, this library won't be able to play it.

**Comment by stardev24** [comment]
Thanks for your comment.I am using Android with latest OS version.
is there any method to get supported language details from headset?

**Comment by ak1394** [comment]
Not through this library. If you can run native code, this looks helpful: https://stackoverflow.com/questions/4872702/get-available-locales-for-text-to-speech-tts
