### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by RailtonMatthew** [ak1394/react-native-tts#2]
Hi, the installation when Ok but when I run the app I get the red screen with the following error:

Native module TextToSpeechModule tried to override TextToSpeechModule for module name TextToSpeech.  If this was your intention, return true from TextToSpeechModule#canOverrideExistingModule()

Thanks, Railton.

**Comment by ak1394** [comment]
I assume you're on Android? Which react-native version are you using?

**Comment by RailtonMatthew** [comment]
Hi, thanks for the reply.  Yes on Android, react-native version is 0.34.1

**MainActivity.java**

```
package com.perfecttimer;

import com.facebook.react.ReactActivity;


public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "PerfectTimer";
    }
}
```

**MainApplication.java**

```
package com.perfecttimer;

import android.app.Application;
import android.util.Log;

import com.facebook.react.ReactApplication;
import net.no_mad.tts.TextToSpeechPackage;
import net.no_mad.tts.TextToSpeechPackage;
import com.ocetnik.timer.BackgroundTimerPackage;
import com.oblador.vectoricons.VectorIconsPackage;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;



import com.dieam.reactnativepushnotification.ReactNativePushNotificationPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new TextToSpeechPackage(),
            new TextToSpeechPackage(),
            new BackgroundTimerPackage(),
            new VectorIconsPackage(),
			new ReactNativePushNotificationPackage()
		);
    }
  };

  @Override
  public ReactNativeHost getReactNativeHost() {
      return mReactNativeHost;
  }
}

```

**Comment by ak1394** [comment]
Ok, this seems to be a problem  - in your MainApplication TextToSpeechPackage is initialized twice, if you remove one of  "new TextToSpeechPackage()" entries it should be fine.

I'm not too sure why did it happen, perhaps some issue with "react-native link" command in react-native 0.34?

**Comment by RailtonMatthew** [comment]
Ok thanks. I will check it tomorrow. I may have run the install or link twice which could explain it. 

Railton.

**Comment by ak1394** [comment]
Glad to know it works!

**Comment by pashute** [comment]
I also had duplicates. They were added by link. But I removed the duplicates and still get the error. 

The import was also duplicated several times. There is now only one. 

    import net.no_mad.tts.TextToSpeechPackage;

TextToSpeechPackage is mentioned only in these two places in this file and nowhere else in the project. 

Searching for `tts` I found several places in the pbxproj such as HEADER_SEARCH_PATH  where backslashes were used as opposed to all the other packages where a forward slash was used. I suppose the C or Java or JS removes the backslash in a string and it should be escaped with an extra backslash. 

I hope that fixes my problem...

**Comment by pashute** [comment]
It didn't fix the problem. I did a gradlew clean and still get the `cannot  find` error.

**Comment by pashute** [comment]
**Please re-open this issue**

**Comment by muditasisodia** [comment]
Hi, I'm facing the same issue as @pashute where after installing and linking, it is unable to `
import net.no_mad.tts.TextToSpeechPackage;` and in override, `new TextToSpeechPackage()`.
