### ISSUE TITLE
`new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.

### ISSUE THREAD

**Issue by hyoretsu** [ak1394/react-native-tts#221]
Title and
```
`new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
```

**Comment by equationalapplications** [comment]
I am also getting this error when I run jest to test rendering.

**Comment by equationalapplications** [comment]
I fixed my error by mocking the native event emitter. (https://stackoverflow.com/questions/70506663/invariant-violation-new-nativeeventemitter-requires-a-non-null-argument)
