### ISSUE TITLE
Broken in iOS 16

### ISSUE THREAD

**Issue by fungilation** [ak1394/react-native-tts#224]
in iPhone 14, iOS 16.0 simulator:

`Tts.setDefaultLanguage('en-US')` errors out, and

`Tts.voices().then(voices => console.log(voices))` has voices being empty array.

**Comment by fungilation** [comment]
Nevermind. Need to install voices on simulator, and iOS 16 has changed voice ids (what was com.apple.ttsbundle.Samantha-premium is now com.apple.voice.enhanced.en-US.Samantha)

**Comment by ngochai27595** [comment]
> Nevermind. Need to install voices on simulator, and iOS 16 has changed voice ids (what was com.apple.ttsbundle.Samantha-premium is now com.apple.voice.enhanced.en-US.Samantha)

How can I know what voice id is preserved after ios 16? Thanks

**Comment by naeemanaeem** [comment]
Even after installing the voices Agnes and Alex, and I can see two rows in the array, but still no sound. Any help is appreciated.

**Comment by yongish** [comment]
How do you direct a user to install a voice?

**Comment by amirhosseinmajdi** [comment]
> Even after installing the voices Agnes and Alex, and I can see two rows in the array, but still no sound. Any help is appreciated.

Any Update?

Sounds are ok and in accessibility of simulator i can hear the sounds of the voices but when I try Tts.speak('Hello, world!', {
  iosVoiceId: 'com.apple.voice.enhanced.en-US.Samantha',
  rate: 0.5,
});
no sound play.
