### ISSUE TITLE
App crashes without errors

### ISSUE THREAD

**Issue by LarsKerff** [ak1394/react-native-tts#24]
I'm having a strange error after installing react-native-tts. The run-android command builds up completely. However when I try to run the app (on physical android device) it crashes without any warning/errors. Neither errors on the debugger-ui. Any idea what it could be?

**Comment by dalinarkholin** [comment]
@LarsKerff I saw something similar and it was because I didn't link the package.

**Comment by ak1394** [comment]
Closing as stale, please comment if the problem recurs.
