### ISSUE TITLE
Can we help with maintaining this library?

### ISSUE THREAD

**Issue by walterholohan** [ak1394/react-native-tts#250]
Hi @ak1394, we are using this library in our app at https://runna.com/ and have made several improvements to the library. I can see that you haven't released anything in quite a while. Our team is happy to become a maintainer if you would like some help. Let me know and I will give you the Github handles of the developers on our team who can help

**Comment by ak1394** [comment]
Hi @walterholohan ! Indeed, I moved away from mobile development and haven't done much with the library lately. I'd be happy for your help, please share your dev's handles.

**Comment by walterholohan** [comment]
Brilliant, could you add the following people

- @walterholohan 
- @jameskenyon
- @ThomasMoran

**Comment by walterholohan** [comment]
Also if possible it would be great if you could let us know the process of doing a new release, my email is walter@runna.com

**Comment by walterholohan** [comment]
Hey @ak1394 , i just merged in an important PR, but we want to get it released to NPM. Can you give us access to do this?

CC @fnazarios

**Comment by walterholohan** [comment]
`walterholohan` please

**Comment by ak1394** [comment]
I've sent an invite on npm

**Comment by walterholohan** [comment]
Great thanks @ak1394. Can you remember what scripts you used in order to ship new releases?

**Comment by ak1394** [comment]
The release process is pretty simple, as the package should only include source files and no native build artifacts. Therefore there is no build step involved.

I typically do something like that:

1. Make sure the version in package.json is as desired
2. Test the release, perhaps use `npm pack` to bundle it, install locally without publishing, etc.
3. Tag the release and push the new tag to Github, create release on Github
4. Publish to npm with `npm publish`

BTW, I've just pushed a change to .npmignore to skip Android build files, but if you have any of these left from native Android/iOS builds I would double check to make sure these are not included in the package

**Comment by ak1394** [comment]
@walterholohan if you like I can publish it

**Comment by walterholohan** [comment]
@ak1394 yes please if you have a spare minute

**Comment by ak1394** [comment]
Published 4.1.1
