### ISSUE TITLE
 ERROR  TypeError: Cannot read property 'speak' of null, js engine: hermes

### ISSUE THREAD

**Issue by AhmetAI** [ak1394/react-native-tts#258]
I'm getting this error:

` ERROR  TypeError: Cannot read property 'speak' of null, js engine: hermes
`

Code:

```

import { StatusBar } from 'expo-status-bar';
import React, { useEffect } from 'react';
import { StyleSheet, Text, View, Button } from 'react-native';
import {SafeAreaView} from "react-native-safe-area-context"
import Tts from 'react-native-tts';


export default function App() {

  function handleSpeak() {
    Tts.speak("Hello")

  }

  return (
    <SafeAreaView>
      <Text>Open up App.js to start working on your app!</Text>
      <Button title='Test' onPress={handleSpeak} />
      <StatusBar style="auto" />
    </SafeAreaView>
  );
}
```

**Comment by shubhambathe1** [comment]
@AhmetAI Not sure if it will help but you can checkout:- [Link](https://github.com/ak1394/react-native-tts/issues/124)

**Comment by AhmetAI** [comment]
I tried configuring the project with react native and it works but not with expo.

**Comment by shubhambathe1** [comment]
I don’t  see any support mentioned for React Native Expo in the library documentation, so I think the library might be supported only for React Native CLI as of now. The author of the library might be the right person to answer your query. Please tag him.
