### ISSUE TITLE
'Node module cannot be null' error

### ISSUE THREAD

**Issue by TheresaWilkin** [ak1394/react-native-tts#30]
After adding this, I got the error 'Node module cannot be null'. Stack trace mentions Tts.NativeEventEmitter as the error source. I don't get the error if I'm not importing/using Tts anywhere.  I'm on React-Native 44.2.

**Comment by tysoncadenhead** [comment]
I got this error too. Any update on why this would be happening?

**Comment by TheresaWilkin** [comment]
I uninstalled it, cleared my NPM cache, and reinstalled, then completely closed everything (simulator, my IDE, etc.) and restarted. Then it worked.

**Comment by tysoncadenhead** [comment]
That worked for me too. Thanks!

**Comment by Symous** [comment]
Just run 'react-native run-ios/run-android' again and this error will disappear. :-)

**Comment by mrhandoko** [comment]
Not working

**Comment by nicotroia** [comment]
This is still happening for me. Trying individual versions of this package and manually linking them but nothing is working. App always crashes at splash screen
