### ISSUE TITLE
Access to new Siri voice in iOS 11?

### ISSUE THREAD

**Issue by fungilation** [ak1394/react-native-tts#37]
New iOS 11 came out with much more natural sounding Siri voice. However, even if the voice is installed in Settings app > General > Accessibility > Voices, for 'en-IE' only Samantha shows up from `Tts.voices()`. Is there any way to access the new Siri voice, if it is exposed natively?

For reference, from README:
```js
Tts.voices().then(voices => console.log(voices));

// Prints:
//
// [ { id: 'com.apple.ttsbundle.Moira-compact', name: 'Moira', language: 'en-IE' },
// ...
// { id: 'com.apple.ttsbundle.Samantha-compact', name: 'Samantha', language: 'en-US' } ]
```

**Comment by ak1394** [comment]
Frankly I don't know; voices() call on IOS invokes [AVSpeechSynthesisVoice speechVoices] and returns the resulting list. Perhaps there is some new API involved?

**Comment by fungilation** [comment]
That is the question. Casual googling doesn't seem to turn up anything on new API access to Siri voice

**Comment by fabianunger** [comment]
@fungilation I just tested it again, seems to work now. All voices that are downloaded via Settings app > General > Accessibility > Voices are working now.

**Comment by ak1394** [comment]
That's good to know! I'm closing this issue then.

**Comment by fungilation** [comment]
Awesome! I see "com.apple.ttsbundle.siri_female_en-US_compact" being available now as listed from tts.voices().

**Comment by fungilation** [comment]
I take that back. com.apple.ttsbundle.siri_female_en-US_compact is not "Siri Female", but "Nicky" (by .name)? Tts.setDefaultVoice("com.apple.speech.voice.Alex ignored") gets ignored, on subsequent Tts.speak().

**Comment by CruelMoney** [comment]
@fungilation Did you find a solution to this?

**Comment by fungilation** [comment]
Nope. Last I checked, listing all the voices doesn't show any I tried that correspond to the newer Siri voice that sounds much more natural and accurate, in iOS 11 and 12.

**Comment by Kailang** [comment]
> Siri voices not available through API

At around 4:40 here:
<https://developer.apple.com/videos/play/wwdc2018/236/>
![image](https://user-images.githubusercontent.com/8486638/50544314-be874400-0bb6-11e9-9880-c412797977a6.png)

**Comment by fungilation** [comment]
Sad indeed. I want Jobs back to fire some idiots there. 😭

**Comment by BeeRated** [comment]
and... for anyone wondering 4+ years and Apple still only allows the iOS user to select the Siri Voices for "Spoken Content"... and us puny Xcode developers aren't allowed to use the Siri Voice when we call synthesizer... even when the iOS user has it selected as their default voice under Spoken Content (e.g. Accessibility - Spoken Content - Speak Selection - Voices).  If the device has a Siri voice selected... apple defaults (at least in the US) back to Samantha a.k.a " that b**** ".  If anyone has found a work around... I'm all ears!! :)
