### ISSUE TITLE
Any way to add delay inline in text

### ISSUE THREAD

**Issue by jeffbonasso** [ak1394/react-native-tts#39]
Is there any way to add a delay in a string you send to the TTS engine?

e.g.
This is some content. [PAUSE for 3 seconds] This is more content.

Somewhere I thought I saw iOS supported inlining a command [[sinc 3000]]

**Comment by ak1394** [comment]
You'd have to implement it yourself in javascript, using Tts.addEventListener() etc. There is no support for it in the library.
