### ISSUE TITLE
Text speed

### ISSUE THREAD

**Issue by fabien-h** [ak1394/react-native-tts#4]
Hi, great package !

Would it be possible to change te the speed at will ?

In `TextToSpeech.m`, after that :

	if ( voice ) {
		utterance.voice = [ AVSpeechSynthesisVoice voiceWithIdentifier: voice ];
	} else if ( _defaultVoice ) {
		utterance.voice = _defaultVoice;
	}

You can add

	if ( rate ) {
		utterance.rate = [ rate doubleValue ];
	}

And for android it’s going to be `tts.setPitch(rate);` as far as I understand.

**Comment by fabien-h** [comment]
Awesome, thank you !

**Comment by ak1394** [comment]
Cheers! Thanks goes to @maslianok for the PR. Android uses setSpeechRate(). There are differences between set rate api parameters on ios and android, so I ended up doing some mapping between the two to unify javascript api, therefore max android speech rate which can be set is about x3.
