### ISSUE TITLE
How to use loudspeaker to speak?

### ISSUE THREAD

**Issue by truongluong1314** [ak1394/react-native-tts#42]
Default it don't use loudspeaker so I must use headphone to listening.

**Comment by asafron** [comment]
I've created a workaround for now, which uses the loudspeaker ALWAYS.
You can see the changes in my fork repo:
https://github.com/Clarizen/react-native-tts

I'll will make it more robust and with an option to choose which output type you would like, and will open a PR soon.

**Comment by DVassilev** [comment]
Would you be able to do this for android too?

**Comment by ak1394** [comment]
Closing as stale issue, please comment it should be reopened.
