### ISSUE TITLE
undefined is not an object (evaluating 'NativeSpeechSynthesizer.stopSpeakingAtBoundary')

### ISSUE THREAD

**Issue by binduchinnasamy** [ak1394/react-native-tts#45]
I am using react-native-tts and it is working perfectly fine in my iOS project, however I get the following error while  my Android app launches in emulator 

"undefined is not an object (evaluating 'NativeSpeechSynthesizer.stopSpeakingAtBoundary') 
 Any help on this is much appreciated.

**Comment by binduchinnasamy** [comment]
Just for the updates, after upgrading to  "react": "16.0.0" and "react-native": "0.50.3", the problem disappeared.

**Comment by gregl83** [comment]
i'm having this issue with *react 16.0.0* and *react-native 0.51.0*

i have run `react-native link`

**Comment by gregl83** [comment]
i made the mistake of using a hot reload after running `react-native link`
after a rebuild the TextToSpeech module was available and functioning as expected.

**Comment by linweiboy** [comment]
i'm having this issue,but this issue is "undefined is not an object (evaluating 'TextToSpeech.speak')"

**Comment by ak1394** [comment]
Closing as stale issue, please comment it should be reopened.

**Comment by aaron97tucker** [comment]
please reopen, i have the same problem
