### ISSUE TITLE
Text To Speech Not working in real device but working in iOS simulator

### ISSUE THREAD

**Issue by binduchinnasamy** [ak1394/react-native-tts#49]
Hello Folks, 
I have a production ready App and using react-native-tts, Text to speech works well in Android (both real device and simulator) and in iOS it works perfectly fine in simulator but not in the real device. Any suggestions to mitigate this?

**Comment by ak1394** [comment]
Sorry, no idea.

**Comment by dmwallace** [comment]
Check if your device is on silent/vibrate mode, in which case text to speech is not audible

**Comment by Adcrazynoga** [comment]
I have the same issues. But i try in android studio emulator both Debug apk and Release apk. Why just Debug apk have sound and Release not have.

**Comment by ayushnawani** [comment]
@binduchinnasamy  @Adcrazynoga  did you find any solution, for me also in real device its not working

**Comment by ZainabShakeel** [comment]
same issue , any guide?

**Comment by jokerhp6789** [comment]
if anyone still encounter this issue  try to switch off the silent mode by the small button in the left side of the phone
