### ISSUE TITLE
Add gradle wrapper to Android project

### ISSUE THREAD

**Issue by sytolk** [ak1394/react-native-tts#54]
https://docs.gradle.org/current/userguide/gradle_wrapper.html

https://stackoverflow.com/questions/25769536/how-when-to-generate-gradle-wrapper-files

and don't forget to commit generated gradle wrapper .jar Because the whole point of the gradle wrapper is to be able, without having ever installed gradle.

**Comment by ak1394** [comment]
Closing as stale issue, please comment it should be reopened.
