### ISSUE TITLE
First call of Tts.speak() takes lots of time to fire tts-start event

### ISSUE THREAD

**Issue by alexandre-lelain** [ak1394/react-native-tts#56]
Hello,

First of all, thank you very much for all that work.

On react-native 0.49.5, I'm trying to make my bot speak using your library. I first call `Tts.speak("some sentence")` once my components are mounted and I call it again a few times later. The first call of the function returns the promise immediately, but it doesn't fire the `tts-start` event and the voice only plays after 20-30 seconds. Whereas after those 30 seconds, calling `Tts.speak()` fires the tts-start event right away and the bot speaks just after the function call. 

I'm running the react-native app on Android 7.0.

Am I missing something ?

**Comment by alexandre-lelain** [comment]
Update : this bug seems to be related to the Android version as I can't reproduce it on Android 6.x

**Comment by ak1394** [comment]
I think you're correct. The library after all is a thin layer on top of the native API.
