### ISSUE TITLE
Audio ducking support

### ISSUE THREAD

**Issue by IjzerenHein** [ak1394/react-native-tts#6]
Hi, I was wondering what your thoughts are on this. I need background audio to be ducked when text-to-speech is played, and unducked when the utterance is finished. Currently on iOS any background audio is paused and never resumed when usibng react-native-tts. I've already got ducking and audio resume working for iOS, but before I start working on the Android I was thinking what your thoughts are on this.

Should ducking be part of this library, or something that should be build externally using the events that are emitted by this library? A penny for your thoughts.

cheers,
Hein

**Comment by ak1394** [comment]
I see this library as a thin layer providing access to platform TTS APIs. I would think, that restarting background audio shouldn't be it's responsibility. However, I'm not sure what's involved in ducking? Could you post code sample or mention APIs you're using?

**Comment by IjzerenHein** [comment]
Of course, here is the said iOS modification I made:
https://gist.github.com/IjzerenHein/608023fb345d4b00f0ebb80ee66f2a08

On initialisation the AudioManager is configured to duck other (inactive app) audio. Then, when text-to-speech is started, the AudioManager is set to active causing the audio of other apps to the ducked. Upon finishing the utterance the audio-manager is set to in-active again, causing the ducking of other apps to seize.

That being said, I share the same sentiment. Ideally this should be part of an react-native audio-manager library. And you can then hookup the events to that library. It would be a little bit of work to implement per app though, but it's doable. Unfortunately I have not found a react-native audio manager that exposes such functionality. I'm also not sure whether such a solution would work on Android though, it might require closer code integration.

As I don't really have an alternative at this stage, I was thinking of adding a function called `tts.enableAudioDucking(true)` that you can call to enable this behavior. What do you think?

**Comment by IjzerenHein** [comment]
Alright, what would you think of me creating a `react-native-audio-duck` library? (If I can make it work for Android as well). And then maybe we can put a small example on the `react-native-tts` readme so other people know how to do it as well?

**Comment by ak1394** [comment]
I looked at your changes and a bit of documentation related to audio session stuff, and I think it's a good idea to move ducking implementation into a different library. I'd be happy to include any samples for integrating the two!

**Comment by IjzerenHein** [comment]
That would be awesome. I'll try to get Android working and keep you posted.

**Comment by ak1394** [comment]
Hi @IjzerenHein ! I ended up adding ducking support directly to tts library, I got another PR asking for the same, so it made me change my mind. The code was pretty much as yours, but I did tweak it a little to make ducking opt-in. BTW, if you've had progress with react-native-audio-duck, let me know!

**Comment by IjzerenHein** [comment]
Hey, thats awesome to hear! Did you also add Android support? I've not gotten around to do any work in this area yet. I'm gonna install the new lib and check whether it works with our app.
Cheers

**Comment by ak1394** [comment]
Yep, it has Android support - I've got PR which implemented both iOS and Android, which I tweaked a bit and merged. The code hasn't been released yet, but is on master branch. I'll release it after a bit of testing in a couple of days.

**Comment by ak1394** [comment]
Just published new release to npm.
