### ISSUE TITLE
Missing documentation for KEY_PARAM_STREAM

### ISSUE THREAD

**Issue by ohtangza** [ak1394/react-native-tts#62]
cc: @sunjae1294

**Comment by ak1394** [comment]
Not sure what's there to document, these keys are documented in Android docs.

**Comment by ak1394** [comment]
Ah, I see. I guess 'cause react-native-tts hardcodes key names, these should indeed be documented. I don't have time for it though, but will accept PR if anyone does it.

**Comment by ohtangza** [comment]
@ak1394 Thanks for your understanding, since my team worked on this, I might open a pull request for this. Thanks for your prompt reply. Have a nice weekend :)
