### ISSUE TITLE
does not build with RN 0.40 (iOS)

### ISSUE THREAD

**Issue by fabien-h** [ak1394/react-native-tts#7]
Due to this : https://github.com/facebook/react-native/releases

> After e1577df, Native code on iOS must refer to headers out of the react namespace. Previously the following would work:

    #import "RCTUtils.h"

> But now all headers have been moved:

    #import <React/RCTUtils.h>

Solution here : in `TextToSpeech.m`, line 9, replace `#import "RCTBridge.h"` by `#import <React/RCTBridge.h>`

And the rest too :

    #import <React/RCTBridge.h>
    #import <React/RCTEventDispatcher.h>
    #import <React/RCTLog.h>
    #import <TextToSpeech/TextToSpeech.h>

I don’t PR because it would break builds on RN < 0.40.

**Comment by ak1394** [comment]
Thanks for heads up! I'm going to fix it in the next day or so. I think bumping major version number and adding proper peerDependency to package.json should give enough warning to existing library users.

**Comment by ak1394** [comment]
Fixed! I never got around doing it myself, but merged @jmfirth 's PR. Thanks!
