### ISSUE TITLE
unable to read special characters, like $

### ISSUE THREAD

**Issue by subham18meme** [ak1394/react-native-tts#70]
hi,
I am trying to parse a sentence with some special characters like :"i need 20 $"
so here dollar is not converted to speech.
Any help will be very helpful

**Comment by ak1394** [comment]
Hey! The actual speech output is controlled by the underlying platform, not the react-native-tts which is a wrapper on top of it. However, obvious solution would be to replace $ signs with "dollar" word in the body of the text you're trying to use.
