### ISSUE TITLE
No voice in Android

### ISSUE THREAD

**Issue by ho1messi** [ak1394/react-native-tts#71]
`
Tts.getInitStatus()
  .then(() => {
    alert('speak');
    Tts.speak('Hello, world!')
  });
`

the alert displayed normally, but no voice.

**Comment by jonnycraze** [comment]
I am getting this as well, was working fine on 4/18

**Comment by ak1394** [comment]
This seem to happen often enough, it seems related to a configuration/state of a particular emulator or a phone.

**Comment by nogamann** [comment]
Is there a fix for that?

**Comment by nogamann** [comment]
@ak1394 for me it works fine for some of the Android devices / versions, but on others it doesn't work at all. Is there a way to solve this? Thank you!
