### ISSUE TITLE
package net.no_mad.tts does not exist error

### ISSUE THREAD

**Issue by aligenc** [ak1394/react-native-tts#72]
I got this error when running react-native run-android:

MainApplication.java:6: error: package net.no_mad.tts does not exist
import net.no_mad.tts.TextToSpeechPackage;

`...

import net.no_mad.tts.TextToSpeechPackage;
import com.zmxv.RNSound.RNSoundPackage;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new TextToSpeechPackage()
      );
    }

  ....
`

**Comment by ak1394** [comment]
Run  react-native link

**Comment by pashute** [comment]
Link did not solve it, nor the solutions here: https://github.com/ak1394/react-native-tts/issues/2
