### ISSUE TITLE
Resolve Promise of speak('') after finish only

### ISSUE THREAD

**Issue by olegsmetanin** [ak1394/react-native-tts#73]
Speak method returns Promise, that resolves immediately. I expected the promise to be resolved right after end of the speaking.
Tts.speak('Hello, world!')
  .then(() => console.log('finish'));

**Comment by ak1394** [comment]
Promise resolves with the utteranceId, which can be used with Tts.addEventListener(...) to track it.

**Comment by Manikandanmk** [comment]
i have call Tts.speak for multiple time also i am printing what it is speaking. But i am not able to print current speaking sentence instead it is showing last sentence. can u help me with this?

**Comment by ak1394** [comment]
On ios there is "tts-progress" event which you can use with Tts.addEventListener() on android you'd likely have to rely on "tts-start"
