### ISSUE TITLE
Use multiple Tts.speak, always respond to the first set of EventListener, there is no way to override or delete the set EventListener

### ISSUE THREAD

**Issue by Scpchao** [ak1394/react-native-tts#80]
componentWillMount() {
       Tts.addEventListener('tts-finish', (event) => console.log("one finish", event));
       Tts.getInitStatus().then(() => {
                  Tts.speak('Hello, one finish');
        });
Tts.removeEventListener('tts-finish', (event) => console.log("one finish", event));
       Tts.getInitStatus().then(() => {
                  Tts.speak('Hello, two finish');
        });
  }

The second time Tts.speak still performs tts-finish Listener,Could not remove Listener

**Comment by ak1394** [comment]
Removing event listener this way won't work. When you call Tts.removeEventListener() you effectively pass it a different function. Try something along the lines of:

componentWillMount() {
this.listener = (event) => console.log("one finish", event);
Tts.addEventListener('tts-finish', this.listener);
Tts.getInitStatus().then(() => {
Tts.speak('Hello, one finish');
});
Tts.removeEventListener('tts-finish', this.listener);
Tts.getInitStatus().then(() => {
Tts.speak('Hello, two finish');
});
}
