### ISSUE TITLE
Ducking fails sometimes on Android with multiple speak invocations

### ISSUE THREAD

**Issue by reyalpsirc** [ak1394/react-native-tts#92]
I have some invocations of `Tts.speak` in different files and I noticed that when they are called multiple times in a short timeframe, the ducking sometimes fails to execute and the background music is mixed with the TTS text.
It seems to me that it probably happens due to the start/stop events being fired in wrong order (since they are not sync)

Is it possible to have a queue mechanism on the library's side so that it only starts the next text once the stop event of the previous text is invoked?

**Comment by ak1394** [comment]
I would prefer to keep this library as close to the native platform APIs as possible. Both iOS and Android APIs allow to enqueue text for speaking and provide events to track the progress.

It should be possible to implement queueing in your app (by using tts-* events).

On the other hand, if you find issues with ducking implementation (which is a part of react-native-tts) I would be happy to receive a bug report of patch.

**Comment by reyalpsirc** [comment]
Okay then. I will close this an implement the queue on the JS side :)
